version: '3.7'

services:
  discovery-service-1.com:
    image: fdobrotv/discovery_service:0.4.0
    hostname: 'discovery-service-1.com'
    environment:
      SPRING_PROFILES_ACTIVE: peerN
      APPLICATION_NAME: discovery-service
      SERVER_PORT: 8761
      HOST_NAME: discovery-service-1.com
      EUREKA_DEFAULT_ZONE: http://discovery-service-2.com:8762/eureka/,http://discovery-service-3.com:8763/eureka/
    ports:
      - "8761:8761"

  discovery-service-2.com:
    image: fdobrotv/discovery_service:0.4.0
    hostname: 'discovery-service-2.com'
    depends_on:
      - discovery-service-1.com
    environment:
      SPRING_PROFILES_ACTIVE: peerN
      APPLICATION_NAME: discovery-service
      SERVER_PORT: 8762
      HOST_NAME: discovery-service-2.com
      EUREKA_DEFAULT_ZONE: http://discovery-service-1.com:8761/eureka/,http://discovery-service-3.com:8763/eureka/
    ports:
      - "8762:8762"

  discovery-service-3.com:
    image: fdobrotv/discovery_service:0.4.0
    hostname: 'discovery-service-3.com'
    depends_on:
      - discovery-service-1.com
    environment:
      SPRING_PROFILES_ACTIVE: peerN
      APPLICATION_NAME: discovery-service
      SERVER_PORT: 8763
      HOST_NAME: discovery-service-3.com
      EUREKA_DEFAULT_ZONE: http://discovery-service-1.com:8761/eureka/,http://discovery-service-2.com:8762/eureka/
    ports:
      - "8763:8763"